name: 测试

on:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
    test:
      name: 同步 lede 仓库
      if: github.event.repository.owner.id == github.event.sender.id  || ! github.event.sender.id
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false

      steps:
        - name: 配置环境
          run: |
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            sudo timedatectl set-timezone "Asia/Shanghai"

        - name: test
          run: |
            cd $GITHUB_WORKSPACE
            git clone --quiet --depth=1 https://github.com/FlawShatter/lede.git temp_rep
            cd temp_rep
            git remote add immortalwrt https://github.com/immortalwrt/immortalwrt.git
            git fetch --all --no-tags
            git checkout -B immortalwrt immortalwrt/master
            rm -rf .github/workflows
            git add .
            git commit -m "Removing workflows files."
            git push "https://${{ secrets.ACCESS_TOKEN }}@github.com/FlawShatter/lede.git" -f HEAD:immortalwrt
